config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :trips, only: [:index, :show]
  resources :trails, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/trail.rb
class Trail < ApplicationRecord
  has_many :trip_trails
  has_many :trips, through: :trip_trails

  def total_number_of_hikes
    trips.count
  end
end

app/models/trip.rb
class Trip < ApplicationRecord
  has_many :trip_trails
  has_many :trails, through: :trip_trails

  def total_hiking_distance
    trails.sum(:length)
  end

  def average_hiking_distance
    trails.average(:length)
  end

  def longest_hiking_distance
    trails.maximum(:length)
  end

  def shortest_hiking_distance
    trails.minimum(:length)
  end
end

app/models/trip_trail.rb
class TripTrail < ApplicationRecord
  belongs_to :trip
  belongs_to :trail
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/trails_controller.rb
class TrailsController < ApplicationController

  def show
    @trail = Trail.find(params[:id])
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  def index
    @trips = Trip.all
  end

  def show
    @trip = Trip.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DayHike</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/trails/show.html.erb
<p><%= @trail.name %></p>
<p><%= @trail.length %></p>
<p><%= @trail.address %></p>
<p>Total number of trips this hike has been included in: <%= @trail.total_number_of_hikes %></p>

app/views/trips/index.html.erb
<% @trips.each do |trip| %>
  <%= link_to trip.name, trip_path(trip) %>
<% end %>

app/views/trips/show.html.erb
<h2><%= @trip.name %></h2>
<p>Total Hiking Distance: <%= @trip.total_hiking_distance %><p>
<p>Average Hiking Distance: <%= @trip.average_hiking_distance %><p>
<p>Longest Hiking Distance: <%= @trip.longest_hiking_distance %><p>
<p>Shortest Hiking Distance: <%= @trip.shortest_hiking_distance %><p>
<% @trip.trails.each do |trail| %>
  <%= trail.name %>
  <%= trail.address %>
  <%= trail.length %>
<% end %>